# Site
#repository: q163i/q163i.github.io
#favicon: images/favicon.png

# Content configuration version
version: 2

# Personal info
name: Roman Litvinov
title: Senior DevOps Engineer | Senior Site Reliability Engineer | Blockchain Engineer
email: roman.o.litvinov@gmail.com
#website: https://q163i.github.io

# Dark Mode (true/false/never)
darkmode: never

# Social links
#twitter_username: facespics
github_username:  q163i
# stackoverflow_username: "00000001"
# dribbble_username: type_me
# facebook_username: type_me
# flickr_username: type_me
#instagram_username: roman.o.litvinov
linkedin_username: q163i
# xing_username: type_me
# pinterest_username: type_me
#youtube_username: type_me
# googleplus_username: +type_me
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: telegram link
  icon: fab fa-telegram
  url: http://t.me/q163i
- title: calendly link
  icon: far fa-calendar
  url: https://calendly.com/q163i

# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/LITVINOV.jpg
about_content: | # this will include new lines to allow paragraphs
  Senior DevSecOps Engineer with 9+ years of experience delivering secure and scalable infrastructure in Web3, AI, and fintech domains. 
  Specialized in CI/CD automation, Kubernetes, Terraform, and multi-cloud environments (AWS/GCP). 
  Proven success in reducing deployment times by 80% and optimizing cost/performance in production systems. 
  Currently focused on secure infra-as-code, GPU-based AI workloads, and validator/node/rpc infrastructure for L1/L2 blockchains. 
  Open to senior roles in high-impact engineering teams.

  <mark>Programming Languages</mark>: Bash, Python, Java, JavaScript, Go, C#, .NET, Ruby, TypeScript, Rust
  
  <mark>Infrastructure & DevOps</mark>: Terraform, Terragrunt, OpenTofu, Ansible, Puppet, Chef, Packer
  
  <mark>Containers & Orchestration</mark>: Docker, Podman, containerd, Kubernetes (k8s/k3s/k0s), OpenShift
  
  <mark>CI/CD & Git</mark>: GitLab, GitHub Actions, Bitbucket, TeamCity, Jenkins, Argo CD
  
  <mark>Cloud Platforms</mark>: AWS, GCP, Azure, OVH, Cloudflare
  
  <mark>Monitoring & Observability</mark>: Grafana (+Loki), Zabbix, Prometheus, Kibana, Graylog, Fluent Bit, Uptime Kuma
  
  <mark>Databases & Analytics</mark>: Oracle, MS SQL Server, PostgreSQL (Patroni), MySQL, MongoDB, Metabase
  
  <mark>Networking & Load Balancing</mark>: Load Balancers (F5, HAProxy, NGINX), Ingress/Egress, VIP/NLB
  
  <mark>Virtualization & Platforms</mark>: Windows, macOS, VMware ESXi, NSX-T, Hyper-V
  
  <mark>Message Queues & Caching</mark>: Redis, Kafka, RabbitMQ, Zookeeper
  
  <mark>Security & Tools</mark>: Trivy, Snyk, Jira, Notion, S3
  
  <mark>AI & Emerging Tech</mark>: OpenAI, Whisper AI, CloudEvents, IoT, N8N
  
  <mark>Methodologies & Practices</mark>: GitOps, DevSecOps, FinOps, Twelve-Factor App, B2B, B2C, SaaS, AI, Agile, Scrum
  
  [Download my last full CV](https://docs.google.com/document/d/1kDngYAP8Ag_7t9Fkd_6H1GPQ3YMk3s5db93BknTY2x4/edit?usp=sharing)

content:
  - title: Certificate's
    layout: text
    content: | # this will include new lines to allow paragraphs
      - SQL Server: Performance Tuning and Optimization 
      - Microsoft SQL Server: AlwaysON Microsoft
      - Windows Server Features Microsoft
      - Azure Synapse SQL Pool - Implement Polybase
      - SQL Server Features and Administration Microsoft
      - Oracle Database 12c: Performance Management and Tuning 
      - Oracle Database 12c R2: Administration Workshop Ed 3 PRV Oracle 
      - HashiCorp Certified: Terraform Associate (003)*
      - AWS Cloud Quest. Cloud Practitioner
      - AWS Getting Started with DevOps
      - AWS Cloud Quest: Practitioner Essentials 
      - AWS Cloud Quest: Solutions Architect

  - title: Community Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: center
        title: watcher_bot
        link_text: Infrastructure Bot
        link: https://github.com/q163i/watcher_bot
        additional_links:
          - title:  q163i/watcher_bot
            icon: fab fa-github
            url: https://github.com/q163i/watcher_bot
        description: | # this will include new lines to allow paragraphs
          The Watcher Bot is a Telegram bot designed to monitor various aspects of your Kubernetes cluster and provide real-time notifications and insights. 
          It offers several features tailored for DevOps and system administrators, making it a valuable tool for managing and maintaining Kubernetes environments.
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Samara State University
        caption: 2010 - 2014
        sub_title: Bachelor Math
      - layout: left
        title: Samara State University of Economics
        caption: 2014 - 2016
        sub_title: Master Law
#  - title: A Little More About Me
#    layout: text
#    content: | # this will include new lines to allow paragraphs
#      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#      - Rock climbing
#      - Gaming
#      - Knitting
#      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

#      Look at this cool image
#      ![Trees](images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
