# Site
#repository: q163i/q163i.github.io
#favicon: images/favicon.png

# Content configuration version
version: 2

# Personal info
name: Roman Litvinov
title: Senior DevOps Engineer | Senior Site Reliability Engineer | Blockchain Engineer
email: roman.o.litvinov@gmail.com
#website: https://q163i.github.io

# Dark Mode (true/false/never)
darkmode: never

# Social links
#twitter_username: facespics
github_username:  q163i
# stackoverflow_username: "00000001"
# dribbble_username: type_me
# facebook_username: type_me
# flickr_username: type_me
#instagram_username: roman.o.litvinov
linkedin_username: q163i
# xing_username: type_me
# pinterest_username: type_me
#youtube_username: type_me
# googleplus_username: +type_me
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: telegram link
  icon: fab fa-telegram
  url: http://t.me/q163i
- title: calendly link
  icon: far fa-calendar
  url: https://calendly.com/q163i

# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/LITVINOV.jpg
about_content: | # this will include new lines to allow paragraphs
  Experienced Senior DevOps Engineer with 9 years in disaster recovery, CI/CD pipelines, and team leadership. Dynamic and results-driven.
  “Exactly the engineer you need”
  
  <mark>Programming Languages</mark>: Bash, Python, Java, JavaScript, Go
  
  <mark>IaC (Infrastructure as Code)</mark>: Terraform, Terragrunt, OpenTofu, Ansible, Puppet, Chef
  
  <mark>Containers & Orchestration:</mark>: Docker, containerd, Podman, Kubernetes (k8s, k3s), OpenShift, Glasscube
  
  <mark>Git + CI/CD</mark>: GitLab, GitHub Actions, Bitbucket, TeamCity, Jenkins, Argo CD
      
  <mark>Repositories</mark>: DockerHub, GitLab Registry, Nexus Registry, Artifactory, GitHub Packages
  
  <mark>Databases</mark>: Oracle 12c, MS SQL Server, MySQL, MariaDB, PostgreSQL (Patroni), MongoDB, Metabase (GUI)
  
  <mark>Cloud Platforms:</mark>: AWS, Google Cloud Platform, Azure, Yandex Cloud, OVH, Cloudflare, Private Clouds
  
  <mark>Monitoring & Logging:</mark>: Grafana (Loki), Zabbix, Prometheus,Graylog, Uptime Kuma, Kibana, Fluent Bit
  
  <mark>Networking</mark>: vIP , NLB, LB, F5, Ingress, Egress
  
  <mark>Additional Tools & Technologies:</mark>:  Redis, Kafka, RabbitMQ, ZooKeeper, Jira, Notion, S3, Trivy, Snyk, OpenAI, Whisper, Twelve-Factor App Methodology

  [Download my last full CV](https://docs.google.com/document/d/1kDngYAP8Ag_7t9Fkd_6H1GPQ3YMk3s5db93BknTY2x4/edit?usp=sharing)

content:
  - title: Certificate's
    layout: text
    content: | # this will include new lines to allow paragraphs
      - SQL Server: Performance Tuning and Optimization 
      - Microsoft SQL Server: AlwaysON Microsoft
      - Windows Server Features Microsoft
      - Azure Synapse SQL Pool - Implement Polybase
      - SQL Server Features and Administration Microsoft
      - Oracle Database 12c: Performance Management and Tuning 
      - Oracle Database 12c R2: Administration Workshop Ed 3 PRV Oracle 
      - HashiCorp Certified: Terraform Associate (003)*
      - AWS Cloud Quest. Cloud Practitioner
      - AWS Getting Started with DevOps
      - AWS Cloud Quest: Practitioner Essentials 
      - AWS Cloud Quest: Solutions Architect

  - title: Community Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: center
        title: watcher_bot
        link_text: Infrastructure Bot
        link: https://github.com/q163i/watcher_bot
        additional_links:
          - title:  q163i/watcher_bot
            icon: fab fa-github
            url: https://github.com/q163i/watcher_bot
        description: | # this will include new lines to allow paragraphs
          The Watcher Bot is a Telegram bot designed to monitor various aspects of your Kubernetes cluster and provide real-time notifications and insights. 
          It offers several features tailored for DevOps and system administrators, making it a valuable tool for managing and maintaining Kubernetes environments.
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Samara State University
        caption: 2010 - 2014
        sub_title: Bachelor Math
      - layout: left
        title: Samara State University of Economics
        caption: 2014 - 2016
        sub_title: Master Law
#  - title: A Little More About Me
#    layout: text
#    content: | # this will include new lines to allow paragraphs
#      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#      - Rock climbing
#      - Gaming
#      - Knitting
#      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

#      Look at this cool image
#      ![Trees](images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag